"""Add favorite_tags to users table

Revision ID: 084e773361a0
Revises: 39794183b420
Create Date: 2025-09-03 13:00:40.341601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084e773361a0'
down_revision = '39794183b420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_tags')

    # ### end Alembic commands ###
