"""Allow guests to trigger notifications

Revision ID: 0d68a74113af
Revises: a0da73b10d9a
Create Date: 2025-08-05 12:55:31.615590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d68a74113af'
down_revision = 'a0da73b10d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=80), nullable=True))
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
