"""Add pubished_at to Posts

Revision ID: 1065b805891c
Revises: 9adb23e61aad
Create Date: 2025-08-23 11:20:40.601072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1065b805891c'
down_revision = '9adb23e61aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
