"""Add soft-delete columns to Comment model

Revision ID: 1233ab03841b
Revises: 
Create Date: 2025-07-11 19:03:29.159827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '1233ab03841b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('comments')]
    if 'is_removed' not in columns:
        op.add_column('comments', sa.Column('is_removed', sa.Boolean(), nullable=False, server_default='0'))
    if 'removed_by' not in columns:
        op.add_column('comments', sa.Column('removed_by', sa.Integer(), nullable=True))
    if 'removed_at' not in columns:
        op.add_column('comments', sa.Column('removed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('removed_at')
        batch_op.drop_column('removed_by')
        batch_op.drop_column('is_removed')

    # ### end Alembic commands ###
