"""Add newsletter subscription model for guests

Revision ID: 39794183b420
Revises: add_bio_fields_to_users
Create Date: 2025-09-03 11:38:50.993514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '39794183b420'
down_revision = 'add_bio_fields_to_users'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_splinters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_splinters_bill_id'))

    op.drop_table('bill_splinters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_splinters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bill_id', sa.INTEGER(), nullable=False),
    sa.Column('quote_text', sa.TEXT(), nullable=False),
    sa.Column('quote_html', sa.TEXT(), nullable=True),
    sa.Column('selector_json', sqlite.JSON(), nullable=True),
    sa.Column('label', sa.VARCHAR(length=32), nullable=False),
    sa.Column('summary', sa.VARCHAR(length=280), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_splinters_bill_id_bills')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_splinters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_splinters_bill_id'), ['bill_id'], unique=False)

    # ### end Alembic commands ###
