"""Add email options

Revision ID: 45a4f2f72f85
Revises: 7690471e4014
Create Date: 2025-08-07 08:12:55.206077

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45a4f2f72f85"
down_revision = "7690471e4014"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("newsletter", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("email_notifications", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("email_notifications")
        batch_op.drop_column("newsletter")

    # ### end Alembic commands ###
