"""Add tags

Revision ID: 54e4d63464a3
Revises: 45a4f2f72f85
Create Date: 2025-08-13 10:17:40.205440

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54e4d63464a3"
down_revision = "45a4f2f72f85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.alter_column(
            "removed_by",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=20),
            existing_nullable=True,
        )

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_posts_updated_at"), ["updated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_updated_at"))

    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.alter_column(
            "removed_by",
            existing_type=sa.String(length=20),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
