"""Add splinters

Revision ID: 784166eed563
Revises: 54e4d63464a3
Create Date: 2025-08-19 19:03:55.164775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784166eed563'
down_revision = '54e4d63464a3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_splinter', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('target_post_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_posts_target_post_id', ['target_post_id'])
        batch_op.create_foreign_key('fk_posts_target_post_id_posts', 'posts', ['target_post_id'], ['id'])

    # This fails in SQLite, so protect it:
    conn = op.get_bind()
    if conn.dialect.name != "sqlite":
        op.alter_column("posts", "is_splinter", server_default=None)




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_target_post_id_posts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posts_target_post_id'))
        batch_op.drop_column('target_post_id')
        batch_op.drop_column('is_splinter')

    # ### end Alembic commands ###
