"""Add drafts

Revision ID: 9adb23e61aad
Revises: 784166eed563
Create Date: 2025-08-22 15:16:59.220708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adb23e61aad'
down_revision = '784166eed563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts") as batch_op:
        batch_op.add_column(
            sa.Column("is_draft", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # Then clean up: remove the default so new rows rely on your app logic
    with op.batch_alter_table("posts") as batch_op:
        batch_op.alter_column("is_draft", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
