"""Add 'updated at' to edited posts

Revision ID: 9d6d12885b93
Revises: 1233ab03841b
Create Date: 2025-07-13 10:02:26.386454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '9d6d12885b93'
down_revision = '1233ab03841b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('posts')]
    if 'updated_at' not in columns:
        op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_updated_at'))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
