"""Add guest comments

Revision ID: a0da73b10d9a
Revises: 723c39014a30
Create Date: 2025-08-03 12:19:21.819025

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0da73b10d9a"
down_revision = "723c39014a30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("guest_name", sa.String(length=80), nullable=True)
        )
        batch_op.alter_column("author_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.alter_column("author_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("guest_name")

    # ### end Alembic commands ###
