"""Add bio fields to users table

Revision ID: add_bio_fields_to_users
Revises: 67a3317b9ff2
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_bio_fields_to_users'
down_revision = '67a3317b9ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if bio fields already exist before adding them
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("users")]
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'bio_text' not in columns:
            batch_op.add_column(sa.Column('bio_text', sa.Text(), nullable=True))
        if 'bio_html' not in columns:
            batch_op.add_column(sa.Column('bio_html', sa.Text(), nullable=True))
        if 'location' not in columns:
            batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        if 'website' not in columns:
            batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        if 'social_links' not in columns:
            batch_op.add_column(sa.Column('social_links', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if bio fields exist before removing them
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("users")]
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'social_links' in columns:
            batch_op.drop_column('social_links')
        if 'website' in columns:
            batch_op.drop_column('website')
        if 'location' in columns:
            batch_op.drop_column('location')
        if 'bio_html' in columns:
            batch_op.drop_column('bio_html')
        if 'bio_text' in columns:
            batch_op.drop_column('bio_text')

    # ### end Alembic commands ###
