"""Add password reset token

Revision ID: c8f9a2b5d3e1
Revises: 084e773361a0
Create Date: 2025-10-12 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8f9a2b5d3e1"
down_revision = "084e773361a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reset_token", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("reset_token_expiry", sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f("ix_users_reset_token"), ["reset_token"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_reset_token"))
        batch_op.drop_column("reset_token_expiry")
        batch_op.drop_column("reset_token")

    # ### end Alembic commands ###

